name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Add explicit permissions
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v5
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint
      run: npm run lint
    
    - name: Run tests
      run: npm test
    
    - name: Build
      run: npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files-node-${{ matrix.node-version }}
        path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      actions: read
    
    steps:
    - uses: actions/checkout@v5
      with:
        # Fetch all history for all branches
        fetch-depth: 0
    
    # Initialize gh-pages branch if it doesn't exist
    - name: Create gh-pages branch if needed
      run: |
        if ! git show-ref --verify --quiet refs/remotes/origin/gh-pages; then
          git checkout --orphan gh-pages
          git reset --hard
          git commit --allow-empty -m "Initial gh-pages commit"
          git push origin gh-pages
          git checkout main
        fi
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-files-node-20.x
        path: dist/
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        # Use deploy key or PAT instead of GITHUB_TOKEN
        deploy_key: ${{ secrets.DEPLOY_KEY }}
        publish_dir: ./dist
        # Enable if you want to keep the deployment history
        keep_files: true
